"""initial

Revision ID: d5e589f3dec4
Revises: 
Create Date: 2023-08-04 16:53:27.357977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e589f3dec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispenser',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('flow_volume', sa.Float(precision=2), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispenser_entries',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('dispenser_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dispenser_id'], ['dispenser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispenser_entries')
    op.drop_table('dispenser')
    # ### end Alembic commands ###
